### ISSUE TITLE
License check action fails

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1138]
See license check error https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/actions/runs/5234252867/jobs/9450266145?pr=1137 reported for https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1137 

```
Error: Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/synccontext/SyncContextFactory
	at org.eclipse.tycho.core.resolver.MavenTargetLocationFactory.resolveTargetDefinitionContent(MavenTargetLocationFactory.java:53)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContentWithExceptions(TargetDefinitionResolver.java:172)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:102)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.resolveFromArguments(TargetDefinitionResolverService.java:93)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.tycho.p2resolver.TargetDefinitionResolverService.getTargetDefinitionContent(TargetDefinitionResolverService.java:68)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.resolveTargetDefinitions(TargetPlatformFactoryImpl.java:214)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:164)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:137)
	at org.eclipse.tycho.p2resolver.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:88)
	at org.eclipse.tycho.p2resolver.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:71)
	at org.eclipse.tycho.p2resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:205)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:[101](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/actions/runs/5234252867/jobs/9450266145?pr=1137#step:10:103))
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$3(TychoMavenLifecycleParticipant.java:269)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.WhileOps$1$1.accept(WhileOps.java:99)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects(TychoMavenLifecycleParticipant.java:305)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:150)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:254)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:[106](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/actions/runs/5234252867/jobs/9450266145?pr=1137#step:10:108))
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.synccontext.SyncContextFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 41 more
Committers can request a review by commenting '/request-license-review'
Error: Process completed with exit code 1.
```

@laeubi : is this a tycho issue or platform (missing dependency) or license check issue?

**Comment by laeubi** [comment]
I proposed a patch here but it seems not getting enough attention to perform any action:

https://github.com/eclipse/dash-licenses/pull/244

**Comment by laeubi** [comment]
This should now be fixed by moving the workflow here.
