### ISSUE TITLE
Build I20231205-1800 is unstable, SWT build broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1640]
See 
* https://download.eclipse.org/eclipse/downloads/drops4/I20231205-1800
* https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/324/ 
* https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/325/
* https://download.eclipse.org/eclipse/downloads/drops4/I20231205-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

The SWT build terminates saying 

```
13:44:03  Caused by: org.apache.maven.surefire.api.util.SurefireReflectionException: java.lang.ClassNotFoundException: com.atlassian.clover.recorder.junit.JUnitTestRunnerInterceptor
13:44:03  	at org.apache.maven.surefire.api.util.ReflectionUtils.loadClass(ReflectionUtils.java:162)
13:44:03  	at org.apache.maven.surefire.api.util.ReflectionUtils.instantiate(ReflectionUtils.java:92)
13:44:03  	at org.apache.maven.surefire.common.junit4.JUnit4RunListenerFactory.createCustomListeners(JUnit4RunListenerFactory.java:39)
13:44:03  	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
13:44:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:44:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
13:44:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:44:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
13:44:03  	at org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:137)
13:44:03  	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:148)
13:44:03  	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:88)
13:44:03  	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:91)
13:44:03  	... 30 more
13:44:03  Caused by: java.lang.ClassNotFoundException: com.atlassian.clover.recorder.junit.JUnitTestRunnerInterceptor
13:44:03  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
13:44:03  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
13:44:03  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
13:44:03  	at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:82)
13:44:03  	at org.apache.maven.surefire.api.util.ReflectionUtils.loadClass(ReflectionUtils.java:160)
13:44:03  	... 41 more
```

Root cause is https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1630

**Comment by iloveeclipse** [comment]
I've triggered SWT build to see if that works now: https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/326/

**Comment by iloveeclipse** [comment]
@jukzi : for the future: I prefer to keep bugs (especially infrastructure related) open until the fix is verified, it makes it easy to find them again if the fix would fail for whatever reason.

Note: I've started SWT build and once it succeeds (and it looks now it will, as tests are running), I plan to start IBuild.

**Comment by iloveeclipse** [comment]
SWT build succeeded, so triggered I Build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/25/

**Comment by iloveeclipse** [comment]
SDK build was successful: https://download.eclipse.org/eclipse/downloads/drops4/I20231206-0410
