### ISSUE TITLE
Latest I-build-4.32 failed in "Gather Eclipse Parts"

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.releng.aggregator#1921]
Console output:

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/27/console

Relevant part of the output:

```
10:39:20  [indexResults] DEBUG: BEGIN: Parsing compile logs and generating summary table.
10:39:20        [ant] Exiting /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/scripts/publish.xml.
10:39:20    [antcall] Exiting /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml.
10:39:20  
10:39:20  BUILD FAILED
10:39:20  /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml:40: The following error occurred while executing this line:
10:39:20  /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse/helper.xml:143: The following error occurred while executing this line:
10:39:20  /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/scripts/publish.xml:64: java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Node.getNodeValue()" because "idNode" is null
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.parseCompileLog(TestResultsGenerator.java:672)
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1018)
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1025)
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.processCompileLogsDirectory(TestResultsGenerator.java:1025)
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.parseCompileLogs(TestResultsGenerator.java:724)
10:39:20  	at org.eclipse.releng.generators.TestResultsGenerator.execute(TestResultsGenerator.java:398)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
10:39:20  	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
10:39:20  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
10:39:20  	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
10:39:20  	at org.apache.tools.ant.Task.perform(Task.java:350)
10:39:20  	at org.apache.tools.ant.Target.execute(Target.java:449)
10:39:20  	at org.apache.tools.ant.Target.performTasks(Target.java:470)
10:39:20  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
10:39:20  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
10:39:20  	at org.eclipse.ant.internal.core.ant.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:32)
10:39:20  	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
10:39:20  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
10:39:20  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
10:39:20  	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
10:39:20  	at org.apache.tools.ant.Task.perform(Task.java:350)
10:39:20  	at org.apache.tools.ant.Target.execute(Target.java:449)
10:39:20  	at org.apache.tools.ant.Target.performTasks(Target.java:470)
10:39:20  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
10:39:20  	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
10:39:20  	at org.eclipse.ant.internal.core.ant.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:32)
10:39:20  	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
10:39:20  	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
10:39:20  	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
10:39:20  	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
10:39:20  	at org.apache.tools.ant.Task.perform(Task.java:350)
10:39:20  	at org.apache.tools.ant.Target.execute(Target.java:449)
10:39:20  	at org.apache.tools.ant.Target.performTasks(Target.java:470)
10:39:20  	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
10:39:20  	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
10:39:20  	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
10:39:20  	at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)
10:39:20  	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
10:39:20  	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:714)
10:39:20  	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:571)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.eclipse.ant.core.AntRunner.run(AntRunner.java:506)
10:39:20  	at org.eclipse.ant.core.AntRunner.start(AntRunner.java:603)
10:39:20  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
10:39:20  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
10:39:20  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
10:39:20  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
10:39:20  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:39:20  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:39:20  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:39:20  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:39:20  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:681)
10:39:20  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:618)
10:39:20  	at org.eclipse.equinox.launcher.Main.run(Main.java:1494)
10:39:20  	at org.eclipse.equinox.launcher.Main.main(Main.java:1467)
10:39:20  
10:39:20  Total time: 17 seconds
10:39:21  An error has occurred. See the log file
10:39:21  /home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/tmp/workspace-publish/.metadata/.log.
10:39:21  + [[ 13 -ne 0 ]]
10:39:21  + echo 'Failed in Gather Eclipse Parts stage'
10:39:21  Failed in Gather Eclipse Parts stage
10:39:21  + exit 1
```

**Comment by laeubi** [comment]
I added a fix here:
- https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/pull/59

but I'm not sure if/how this is picked up by the ibuilds, the line numbers at least seem not matching...

**Comment by akurtakov** [comment]
One has to run https://ci.eclipse.org/releng/job/EclipseBuildTools to get a "build" and then run https://ci.eclipse.org/releng/job/ep-deploy-build-tools/ to deploy. I would really appreciate if someone makes https://ci.eclipse.org/platform/job/eclipse.platform.releng.buildtools/ deploy to respective place directly.

**Comment by akurtakov** [comment]
Looking at https://ci.eclipse.org/releng/job/ep-deploy-build-tools/configure there are both product zip and p2 repo. I can't say whether the product zip is needed at all that has to be investigated and eventually removed and only the p2 repo used to install on top of latest release as otherwise buildtools product with all the fuzz around it has to be created.

**Comment by akurtakov** [comment]
@sravanlakkimsetti Maybe you can share some light here.

**Comment by akurtakov** [comment]
I'll trigger new I-build.

**Comment by laeubi** [comment]
I think this broke the build now https://github.com/eclipse-jdt/eclipse.jdt.core/commit/df543ef70f9f270d476c58fdfb3d9451907d6e89

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti Maybe you can share some light here.

Let me take a look

**Comment by sravanlakkimsetti** [comment]
@akurtakov in https://download.eclipse.org/eclipse/updates/buildtools/ you'll see a zip file and extracted folder. Here content is same for both I used zip format to transfer the p2 repo from EclipseBuildTools job to download location. 

Just for the convenience I used xp file for transfer. once the p2 repo is deployed. you can get rid of zip file.
