### ISSUE TITLE
Outdated JDTTipProvider?

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.releng.aggregator#2135]
Sometimes after running junit tests i get message `Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.tips.ide.internal.IDETipManager$1`

The stacktrace of that job is:
```
	 at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	 at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46)
	 at java.base/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:256)
	 at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:307)
	 at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	 at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	 at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	 at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
	 at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
	 at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	 at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461)
	 at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066)
	 at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	 at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	 at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	 at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	 at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827)
	 at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
	 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
	 at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	 at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3235)
	 at java.base/java.net.HttpURLConnection.getHeaderFieldDate(HttpURLConnection.java:603)
	 at java.base/java.net.URLConnection.getLastModified(URLConnection.java:569)
	 at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getLastModified(HttpsURLConnectionImpl.java:391)
	 at org.eclipse.jdt.tips.user.internal.JDTTipProvider.getLastModifiedDate(JDTTipProvider.java:148)
	 at org.eclipse.jdt.tips.user.internal.JDTTipProvider.fetchContent(JDTTipProvider.java:66)
	 at org.eclipse.jdt.tips.user.internal.JDTTipProvider.loadNewTips(JDTTipProvider.java:48)
	 at org.eclipse.tips.ide.internal.IDETipManager$1.run(IDETipManager.java:94)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
It tries to download https://eclipse.mirror.liteserver.nl/eclipse/tips/org.eclipse.jdt.tips.user/provider.json which responds very lazy.
The last tip is from "2018-06-05"

As the Tips seem to be outdated can we just remove or disable that TipProvider?

**Comment by akurtakov** [comment]
@noopur2507 Can you answer this question? Or if you can't do you know who can?

**Comment by noopur2507** [comment]
@wimjongman should be able to answer this.

**Comment by wimjongman** [comment]
Those are general JDT tips which are still valid today. The content definitely needs some love. The slowness is due to a failing mirror, which is a separate issue.

As for disabling the provider: The team has to decide if they want to keep the tips. If they do, we need to define some releng processes to maintain the tips on a regular basis. I'm happy to help here.

This should be discussed in a separate issue higher up the chain.

**Comment by akurtakov** [comment]
@wimjongman where are the tips maintained ? to start with.

**Comment by wimjongman** [comment]
@akurtakov 
The tips framework is here: https://github.com/eclipse-platform/eclipse.platform/tree/master/ua
Our providers are here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.common/bundles

**Comment by wimjongman** [comment]
The tip provider determines where the tips come from. They can come from the wiki, a local directory, a download location. 

The dynamic setup of the providers was too ambitious. If we want to keep it, it should be tuned down to a local set of tips that can be maintained more easily and without the networking complexity it has today.
