### ISSUE TITLE
BuildTests.testPluginFiles fails since I20220409-1220

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#217]
See
https://download.eclipse.org/eclipse/downloads/drops4/I20220410-1800/testresults/html/org.eclipse.releng.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

The test below fails since https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/14a64d94bc223b53cf223ce657adb177d92fd782

```
java.lang.AssertionError: Plugin directory missing required files: 
/home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java11/workarea/I20220410-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.objectweb.asm_9.3.0.jar; 
/home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java11/workarea/I20220410-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.objectweb.asm.source_9.3.0.jar; 
/home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java11/workarea/I20220410-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.objectweb.asm.tree_9.3.0.jar; 
/home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java11/workarea/I20220410-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.objectweb.asm.tree.source_9.3.0.jar;
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.releng.tests.BuildTests.testPluginFiles(BuildTests.java:422)
```

**Comment by iloveeclipse** [comment]
@mickaelistria : could you please check that?

**Comment by akurtakov** [comment]
Good idea. I'll amend.
