### ISSUE TITLE
Build org.eclipse.rt.osgistarterkit.product failed

### ISSUE THREAD

**Issue by Sakura286** [eclipse-platform/eclipse.platform.releng.aggregator#2391]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

I am trying to build eclipse SDK both on my local x86_64 and riscv64 machine:

```shell
mvn clean verify -Dskiptests=true -Dtycho.version=4.0.8
```

But `org.eclipse.rt.osgistarterkit.product` failed for lack of `org.eclipse.equinox.launcher.cocoa.macosx`

## Here is some relevant log output

```java
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - org.eclipse.test.feature 3.9.0-SNAPSHOT ............ SUCCESS [  0.897 s]
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - org.eclipse.sdk.tests.feature 4.34.0-SNAPSHOT ...... SUCCESS [  1.336 s]
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - eclipse.platform.releng.tychoeclipsebuilder 4.34.0-SNAPSHOT SUCCESS [  0.003 s]
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - org.eclipse.rt.osgistarterkit.product 4.34.0-SNAPSHOT FAILURE [  7.168 s]
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - equinox-sdk 4.34.0-SNAPSHOT ........................ SKIPPED
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - eclipse-junit-tests 4.34.0-SNAPSHOT ................ SKIPPED
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - eclipse.platform.repository 4.34.0-SNAPSHOT ........ SKIPPED
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - platform-aggregator 4.34.0-SNAPSHOT ................ SKIPPED
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
15:44:24,165 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - Total time:  12:53 min
15:44:24,166 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2024-09-26T15:44:24+08:00
15:44:24,166 [main] [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:4.0.8:materialize-products (materialize-products) on project org.eclipse.rt.osgistarterkit.product: Installation of product org.eclipse.rt.osgistarterkit.product for environment macosx/cocoa/aarch64 failed: Call to p2 director application failed:Cannot complete the install because one or more required items could not be found.: [Software being installed: EclipseRT OSGi Starter Kit 4.34.0.I20240926-0731 (org.eclipse.rt.osgistarterkit.product 4.34.0.I20240926-0731); Missing requirement for filter properties ~= $0: org.eclipse.rt.osgistarterkit.product.executable.cocoa.macosx.aarch64 4.34.0.I20240926-0731 requires 'org.eclipse.equinox.p2.iu; org.eclipse.equinox.launcher.cocoa.macosx 0.0.0, filter=(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))' but it could not be found; Cannot satisfy dependency:: [From: EclipseRT OSGi Starter Kit 4.34.0.I20240926-0731 (org.eclipse.rt.osgistarterkit.product 4.34.0.I20240926-0731); To: org.eclipse.equinox.p2.iu; toolingorg.eclipse.rt.osgistarterkit.product.application [4.34.0.I20240926-0731,4.34.0.I20240926-0731]]; Cannot satisfy dependency:: [From: toolingorg.eclipse.rt.osgistarterkit.product.application 4.34.0.I20240926-0731; To: org.eclipse.equinox.p2.iu; org.eclipse.rt.osgistarterkit.product.executable.cocoa.macosx.aarch64 [4.34.0.I20240926-0731,4.34.0.I20240926-0731], filter=(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))]]. Program arguments were: [-metadataRepository, file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/target/targetPlatformRepository/, -artifactRepository, file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/target/,file:/resolution-context-artifacts@%252Fhome%252Finfinity%252FDesktop%252Feclipse%252Feclipse.platform.releng.aggregator-2%252Feclipse.platform.releng.tychoeclipsebuilder%252Fequinox.starterkit.product,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.preferences/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.registry/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.common/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform/runtime/bundles/org.eclipse.core.jobs/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform/runtime/bundles/org.eclipse.core.jobs/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.app/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.concurrent/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi.services/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.app/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.common/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.concurrent/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.console/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.console/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi.util/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.simpleconfigurator/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi.compatibility.state/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/features/org.eclipse.equinox.core.feature/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher.gtk.linux.x86_64/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/features/org.eclipse.equinox.executable.feature/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.frameworkadmin/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.frameworkadmin/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.frameworkadmin.equinox/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.frameworkadmin.equinox/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.http.service.api/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.artifact.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.metadata/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.core/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.jarprocessor/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.artifact.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.console/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.director/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.engine/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.console/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.core/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.garbagecollector/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.metadata.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.touchpoint.eclipse/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.touchpoint.natives/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.simpleconfigurator.manipulator/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.transport.ecf/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.operations/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.linux/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/features/org.eclipse.equinox.p2.core.feature/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.director/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.engine/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.garbagecollector/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.jarprocessor/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.metadata/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.metadata.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.operations/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.repository/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.touchpoint.eclipse/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.touchpoint.natives/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.p2.transport.ecf/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.preferences/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.registry/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.linux/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.simpleconfigurator/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox.p2/bundles/org.eclipse.equinox.simpleconfigurator.manipulator/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi.compatibility.state/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.osgi.services/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher.win32.win32.x86_64/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.win32/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.win32/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher.cocoa.macosx.x86_64/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.macosx/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.security.macosx/target/,file:/home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/equinox/bundles/org.eclipse.equinox.launcher.cocoa.macosx.aarch64/target/,file:/home/infinity/.m2/repository/, -installIU, org.eclipse.rt.osgistarterkit.product, -destination, /home/infinity/Desktop/eclipse/eclipse.platform.releng.aggregator-2/eclipse.platform.releng.tychoeclipsebuilder/equinox.starterkit.product/target/products/org.eclipse.rt.osgistarterkit.product/macosx/cocoa/aarch64/Rt.app, -profile, SDKProfile, -profileProperties, org.eclipse.update.install.features=true, -roaming, -p2.os, macosx, -p2.ws, cocoa, -p2.arch, aarch64]. -> [Help 1]
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - 
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - 
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - 
15:44:24,304 [main] [ERROR] org.apache.maven.cli.MavenCli - After correcting the problems, you can resume the build with the command
15:44:24,305 [main] [ERROR] org.apache.maven.cli.MavenCli -   mvn <args> -rf :org.eclipse.rt.osgistarterkit.product
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText
	... 2 more

```

## Tested under this environment:
* Debian Sid (on x86_64 and riscv64)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by Sakura286** [comment]
Is this issue relevant to https://github.com/eclipse-equinox/equinox/commit/773fe3966 ?

**Comment by akurtakov** [comment]
Please use tycho 4.0.9. IIRC it contains a fix that allow this removal.

**Comment by yuzibo** [comment]
Now I faced another issue to build this.

Based on f7223065ffd8, if ` mvn clean verify  -DskipTests=true`, I get the below log:
```
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-document-bundle-plugin:4.0.9:schema-to-html (sch
ema-to-html) on project org.eclipse.platform.doc.isv: Execution schema-to-html of goal org.eclipse.tycho.extra
s:tycho-document-bundle-plugin:4.0.9:schema-to-html failed: A required class was missing while executing org.e
clipse.tycho.extras:tycho-document-bundle-plugin:4.0.9:schema-to-html: org/eclipse/pde/internal/core/XMLDefaul
tHandler
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.tycho.extras:tycho-document-bundle-plugin:4.0.9
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/debian/.m2/repository/org/eclipse/tycho/extras/tycho-document-bundle-plugin/4.0.9
/tycho-document-bundle-plugin-4.0.9.jar
...
```

**Comment by merks** [comment]
There have been infrastructure issues today.  Perhaps that was the cause?

**Comment by yuzibo** [comment]
> There have been infrastructure issues today. Perhaps that was the cause?

Not sure. I delete the repo and clone it again to start.

**Comment by yuzibo** [comment]
Unfortunately, it still failed from very clean space. the log is [here](https://gist.github.com/yuzibo/35ea8841e42fa3fb289a3a60bcbc7d5d)

**Comment by akurtakov** [comment]
Do you still face the problem with latest master, tycho 4.0.10, maven 3.9.9?

**Comment by Sakura286** [comment]
I don't sure. But since riscv64 artifact has been successfully built, this issue could be closed.
