### ISSUE TITLE
1448 failures jdt.ui.tests for linux.gtk.x86_64 java17 since I20241025-1840

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#2480]
## Steps to reproduce

In the [test results for the latest I-build I20241025-1840](https://download.eclipse.org/eclipse/downloads/drops4/I20241025-1840/testResults.php) there are 1448 failures in the [`jdt.ui.tests` for linux.gtk.x86_64 java 17](https://download.eclipse.org/eclipse/downloads/drops4/I20241025-1840/testresults/html/org.eclipse.jdt.ui.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html).

Most of them are similar to
```
Multiple Failures (2 failures) org.eclipse.core.internal.resources.ResourceException: Resource '/TestSetupProject' does not exist. org.eclipse.jdt.core.JavaModelException: TestSetupProject does not exist

org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
org.eclipse.core.internal.resources.ResourceException: Resource '/TestSetupProject' does not exist.
org.eclipse.jdt.core.JavaModelException: TestSetupProject does not exist
Suppressed: org.eclipse.core.internal.resources.ResourceException: Resource '/TestSetupProject' does not exist.
at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:364)
at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:238)
at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:183)
at org.eclipse.core.internal.resources.Folder.assertCreateRequirements(Folder.java:43)
at org.eclipse.core.internal.resources.Folder.create(Folder.java:101)
at org.eclipse.core.internal.resources.Folder.create(Folder.java:129)
at org.eclipse.jdt.internal.ui.util.ResourcesUtility.createFolder(ResourcesUtility.java:77)
at org.eclipse.jdt.internal.ui.util.CoreUtility.createFolder(CoreUtility.java:64)
at org.eclipse.jdt.testplugin.JavaProjectHelper.addSourceContainer(JavaProjectHelper.java:709)
at org.eclipse.jdt.testplugin.JavaProjectHelper.addSourceContainer(JavaProjectHelper.java:687)
at org.eclipse.jdt.testplugin.JavaProjectHelper.addSourceContainer(JavaProjectHelper.java:673)
at org.eclipse.jdt.testplugin.JavaProjectHelper.addSourceContainer(JavaProjectHelper.java:660)
at org.eclipse.jdt.testplugin.JavaProjectHelper.addSourceContainer(JavaProjectHelper.java:648)
at org.eclipse.jdt.ui.tests.quickfix.AdvancedQuickAssistTest.setUp(AdvancedQuickAssistTest.java:88)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.lang.Exception: Resource '/TestSetupProject' does not exist.
at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
... 15 more
Suppressed: Java Model Exception: Error in Java Model (code 969): TestSetupProject does not exist
at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:546)
at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2533)
at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2329)
at org.eclipse.jdt.internal.core.JavaProject.getOutputLocation(JavaProject.java:2144)
at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3512)
at org.eclipse.jdt.testplugin.JavaProjectHelper.lambda$1(JavaProjectHelper.java:581)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2477)
at org.eclipse.jdt.testplugin.JavaProjectHelper.clear(JavaProjectHelper.java:589)
at org.eclipse.jdt.ui.tests.quickfix.AdvancedQuickAssistTest.tearDown(AdvancedQuickAssistTest.java:93)
at java.base/java.lang.reflect.Method.invoke(Method.java:568) 
```

In general https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2005 could be a cause, because now also the Java-17 tests run with `-Djava.security.manager=allow`. But as far as I know that option should already be available on Java-17 and all other tests don't seem to have a problem with that. Furthermore I don't know how this option can affect the availability of resources.

On the other hand I didn't found a recent change in JDT that seems to be related.
So maybe it's caused by a change in eclipse.platform(.ui)?

@iloveeclipse do you have any idea?

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by iloveeclipse** [comment]
Typically this is a problem from one single test not properly terminated / cleaned up, so all others using same infrastructure simply fail.

**Comment by HannesWell** [comment]
Ok, then lets see if tonight's I-build suffers the same failures or not.

**Comment by HannesWell** [comment]
Today all jdt tests passed on that machine. 
So this was just a temporary flaw.
