### ISSUE TITLE
The eclipse-test-framework deliverable contains unsigned bundles

### ISSUE THREAD

**Issue by mbooth101** [eclipse-platform/eclipse.platform.releng.aggregator#32]
For example from the latest I-build:

https://download.eclipse.org/eclipse/downloads/drops4/I20220216-1800/download.php?dropFile=eclipse-test-framework-I20220216-1800.zip

If you try to install this in Eclipse you get the "Trust" dialog for mockito and friends due to missing GPG signatures.

I believe this to be caused by a bug in Tycho, see bug https://github.com/eclipse/tycho/issues/658

**Comment by akurtakov** [comment]
@mbooth101 can we close this one now ?

**Comment by akurtakov** [comment]
@laeubi Maybe you know whether this one is fixed?

**Comment by merks** [comment]
Note though that https://download.eclipse.org/eclipse/downloads/drops4/I20220313-1800/eclipse-test-framework-I20220313-1800.zip does contain those pgp.signatures and pgp.publicKeys properties so it's some issue related to how the eclipse-test-framework zip/repo is produced...

**Comment by laeubi** [comment]
Tycho 2.7.0 should copy the properties but I have no idea how these zips are actually produced :-)

**Comment by sravanlakkimsetti** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/6c1fa8624342e9f62d19da7a2eb56ccde344128d/cje-production/mbscripts/mb300_gatherEclipseParts.sh#L118 is the place where this zip is produced.

**Comment by laeubi** [comment]
Any reason why this uses a product instead of a `categroy.xml` (haven't check if this makes any difference)

**Comment by sravanlakkimsetti** [comment]
> Any reason why this uses a product instead of a `categroy.xml` (haven't check if this makes any difference)

Probably legacy code from years ago. Not sure when this was first introduced

**Comment by laeubi** [comment]
Alright, actually we have invested a bunch of effort to copy properties and there is even an integration test for this: https://github.com/eclipse/tycho/tree/master/tycho-its/projects/p2Repository.propertyPropagation if anyone finds something missing it would we good to enhance that testcase and open an issue/PR with tycho.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/104 should be a good fix, or at least a necessary steps towards a fix.

**Comment by merks** [comment]
I wanted to see if I could reproduce such a problem, primarily to see if the properties are present in the source `<url>${project.baseUri}/target/repository</url>` and for Tycho 3.0.0 SNAPSHOT those properties are present, but then the build fails with an NPE like this:
```
[INFO] Installing product org.eclipse.oomph.setup.installer.product for environment win32/win32/x86_64 to D:\Users\merks\oomph-master-1.24\git\org.eclipse.oomph\products\org.eclipse.oomph.setup.installer.product\target\products\org.eclipse.oomph.setup.installer.product\win32\win32\x86_64
Installing org.eclipse.oomph.setup.installer.product 1.25.0.v20220314-1144.
Installation failed.
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
	session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
	NullPointerException
	Caused by: 
	java.lang.NullPointerException
There were errors. See log file: D:\Users\merks\oomph-master-1.24\git\org.eclipse.oomph\workspace\.metadata\.log
```
These line numbers seem out of sync with the latest source:
```
!MESSAGE NullPointerException
!STACK 0
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.buildPGPTrustore(CertificateChecker.java:292)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:117)
	at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:73)
	at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:63)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
	at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:46)
	at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:27)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.executePlan(DirectorApplication.java:772)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.planAndExecute(DirectorApplication.java:762)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.performProvisioningActions(DirectorApplication.java:743)
	at org.eclipse.equinox.internal.p2.director.app.DirectorApplication.run(DirectorApplication.java:1066)
	at org.eclipse.tycho.p2.tools.director.DirectorApplicationWrapper$DirectorApplicationWrapperCommand.execute(DirectorApplicationWrapper.java:47)
	at org.eclipse.tycho.plugins.p2.director.DirectorMojo.execute(DirectorMojo.java:153)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```
I also test the mirror application in the SDK IDE and it too replicates the pgp properties...

**Comment by laeubi** [comment]
> These line numbers seem out of sync with the latest source:

Tycho is always one release behind eclipse regarding P2.

**Comment by mickaelistria** [comment]
@mbooth101 Do you really need signed artifacts? The other "Eclipse Automated Tests" package is a not-signed RCP application, and it's not really an issue. I don't think we really need to care about signing (and for the future, I would even say shipping) those test artifacts in a dedicated p2 repository.
